site_name: 'Portfolio Documentation'
site_author: 'mark-middendorf'

theme:
  name: readthedocs

nav:
  - Home: 'index.md'
  - 'HP Portfolio':
    - 'Overview': 'portfolio-hp/_overview.md'
    - 'FRED and Data Mining': 'portfolio-hp/fred-data-mining.md'