site_name: 'Portfolio Documentation'
site_author: 'mark-middendorf'

theme:
  name: readthedocs

nav:
  - Home: 'index.md'
  - 'HP Portfolio':
    - 'FRED and Data Mining': '/portfolio-hp/fred-data-mining.md'